### ISSUE TITLE
Figure out the cause of this error when using proxyquire with handlebars

### ISSUE THREAD

**Issue by joshbedo** [joshbedo/whack-a-mole#10]
```bash
josh$ gulp test
[02:38:13] Using gulpfile /Volumes/Backup/projects/whack-a-mole/gulpfile.js
[02:38:13] Starting 'symlink'...
[02:38:13] src symlinked to node_modules/src
[02:38:13] Finished 'symlink' after 139 ms
[02:38:13] Starting 'mocha'...


  game/module
    #initialize

/Volumes/Backup/projects/whack-a-mole/src/game/template.hbs:1
(function (exports, require, module, __filename, __dirname) { <div class="inde
                                                              ^
      1) "before each" hook


  0 passing (26ms)
  1 failing

  1) game/module "before each" hook:
     SyntaxError: Unexpected token <
      at Module._compile (module.js:439:25)
      at Object.Module._extensions..js (module.js:474:10)
      at Object.require.extensions.(anonymous function) (/Volumes/Backup/projects/whack-a-mole/node_modules/proxyquire/lib/proxyquire.js:246:43)
      at Module.load (module.js:356:32)
      at Function.Module._load (module.js:312:12)
      at Proxyquire._require (/Volumes/Backup/projects/whack-a-mole/node_modules/proxyquire/lib/proxyquire.js:167:19)
      at require (module.js:380:17)
      at Object.<anonymous> (/Volumes/Backup/projects/whack-a-mole/src/game/view.js:2:16)
      at Module._compile (module.js:456:26)
      at Object.Module._extensions..js (module.js:474:10)



[02:38:13] 'mocha' errored after 542 ms
[02:38:13] Error in plugin 'gulp-mocha'
Message:
    1 test failed.
```

**Comment by joshbedo** [comment]
It was due to the view being required and not referenced with proxyquire inside of the test.
